---
format: pdf
lang: pt
title: Atividade 1
subtitle: Probabilidade Condicional
author: Paulo Ricardo Seganfredo Campana
date: 2023-07-18
date-format: long
callout-icon: false
---

::: hidden
\pagestyle{empty}
\thispagestyle{empty}
\def \p #1{{ \text{P} \kern-2pt \left( #1 \right) }}
\def \pc #1#2{{ \text{P} \kern-2pt \left( #1 \; \Big\rvert \; #2 \right) }}
:::

Considere um espaço de probabilidade $(\Omega, \mathcal A, \text{P})$ e assuma que todos os eventos mencionados embaixo pertencem à $\sigma$-álgebra $\mathcal A$.

::: {.callout-warning}
#
Note que se os eventos $D_i$ são disjuntos, então $C \cap D_i$ também são disjuntos e podemos aplicar o terceiro axioma de probabilidade em $\p{\bigcup_i (C \cap D_i)}$.
:::

::: {.callout-note}
###### a) Mostre que se os eventos $D_i$ são disjuntos e $\pc{C}{D_i} = p$, para todo $i$, então $\pc{C}{\bigcup_i D_i} = p$.

$$
\pc{C}{D_i} = \dfrac{\p{C \cap D_i}}{\p{D_i}} = p
$$
$$
\p{D_i} = \dfrac{1}{p} \p{C \cap D_i}
$$

$$
\kern-6pt \pc{C}{\bigcup_i D_i} = 
\dfrac{\p{C \cap \bigcup_i D_i}}{\p{\bigcup_i D_i}} =
\dfrac{\p{\bigcup_i (C \cap D_i)}}{\p{\bigcup_i D_i}} =
\dfrac{\sum_i \p{C \cap D_i}}{\sum_i \p{D_i}} =
\dfrac{\sum_i \p{C \cap D_i}}{\sum_i \frac{1}{p} \p{C \cap D_i}} =
p
$$
:::

::: {.callout-note}
# b) Mostre que se os eventos $C_i$ são disjuntos, então $\pc{\bigcup_i C_i}{D} = \sum_i \pc{C_i}{D}$.

$$
\pc{\bigcup_i C_i}{D} =
\dfrac{\p{D \cap \bigcup_i C_i}}{\p{D}} =
\dfrac{\p{\bigcup_i (C_i \cap D)}}{\p{D}} =
\dfrac{\sum_i \p{C_i \cap D}}{\p{D}} = 
\sum_i \pc{C_i}{D} 
$$
:::

::: {.callout-note}
# c) Mostre que se os eventos $E_i$ são disjuntos e $\bigcup_i E_i = \Omega$, então \qquad\qquad\qquad\qquad \linebreak $\pc{C}{D} = \sum_i \pc{E_i}{D} \pc{C}{E_i \cap D}$.

$$
\sum_i \pc{E_i}{D} \pc{C}{E_i \cap D} =
\sum_i \dfrac{\p{E_i \cap D}}{\p{D}} \dfrac{\p{C \cap E_i \cap D}}{\p{E_i \cap D}} = 
$$
$$
\sum_i \dfrac{\p{C \cap E_i \cap D}}{\p{D}} = 
\sum_i \pc{C \cap E_i}{D} =
$$
$$
\pc{\bigcup_i (C \cap E_i)}{D} =
\pc{C \cap \bigcup_i E_i}{D} =
\pc{C \cap \Omega}{D} =
\pc{C}{D}
$$
:::

::: {.callout-note}
# d) Mostre que se os eventos $C_i$ são disjuntos e $\pc{A}{C_i} = \pc{B}{C_i}$, para todo $i$, então $\pc{A}{\bigcup_i C_i} = \pc{B}{\bigcup_i C_i}$.

$$
\pc{A}{C_i} = \pc{B}{C_i}
\implies
\dfrac{\p{A \cap C_i}}{\p{C_i}} = \dfrac{\p{B \cap C_i}}{\p{C_i}}
\implies
\p{A \cap C_i} = \p{B \cap C_i}
$$

---

$$
\pc{A}{\bigcup_i C_i} =
\dfrac{\p{A \cap \bigcup_i C_i}}{\p{\bigcup_i C_i}} =
\dfrac{\p{\bigcup_i (A \cap C_i)}}{\p{\bigcup_i C_i}} =
\dfrac{\sum_i \p{A \cap C_i}}{\sum_i \p{C_i}}
$$
$$
\dfrac{\sum_i \p{B \cap C_i}}{\sum_i \p{C_i}} =
\dfrac{\p{\bigcup_i (B \cap C_i)}}{\p{\bigcup_i C_i}} =
\dfrac{\p{B \cap \bigcup_i C_i}}{\p{\bigcup_i C_i}} =
\pc{B}{\bigcup_i C_i}
$$

:::