---
format: pdf
lang: pt
title: Atividade 4
subtitle: Convergência estocástica
author: Paulo Ricardo Seganfredo Campana
date: 2023-05-03
date-format: long
---

::: hidden
\pagestyle{empty}
\thispagestyle{empty}
\def \limseq #1{{ \displaystyle \lim_{n \to \infty} #1 }}
\def \p #1{{ \text{P} \kern-2pt \left( #1 \right) }}
\def \E #1{{ \text{E} \kern-2pt \left( #1 \right) }}
\def \Var #1{{ \text{Var} \kern-2pt \left( #1 \right) }}
:::

# 1.
Seja ($A_n$) sequência de eventos em ($\Omega, \mathcal F, \text{P}$). $\forall n$, defina $X_n = \mathbb 1_{A_n}$ (indicadora de $A_n$).

Mostre que $\p{A_n} \longrightarrow 0 \Longleftrightarrow X_n \overset{\text{P}} \longrightarrow 0$.

\begin{align*}
    X_n \overset{\text{P}} \longrightarrow 0 
    &\Longleftrightarrow \limseq{\p{|X_n - 0| > \varepsilon}} = 0 \\
    &\Longleftrightarrow \limseq{\p{|\mathbb 1_{A_n}| > \varepsilon}} = 0 \\
    &\Longleftrightarrow \limseq{\p{\mathbb 1_{A_n} = 1}} = 0 \\
    &\Longleftrightarrow \limseq{\p{A_n}} = 0 \\
    &\Longleftrightarrow \p{A_n} \longrightarrow 0 \\
\end{align*}

{{< pagebreak >}}

# 2.
Seja ($X_n$) sequência de variáveis aleatórias tal que $\E{X_n} = \alpha$ para todo $n$ e $\Var{X_n} \longrightarrow 0$ quando $n \to \infty$. Mostre que $X_n \overset{\text{P}} \longrightarrow \alpha$ (Dica: use a desigualdade clássica de Chebyshev).

Seja $\varepsilon > 0$ qualquer: 

\begin{align*}
    \p{|X_n - \E{X_n}| \geq \varepsilon} &\leq \frac{1}{\varepsilon^2} \Var{X_n} \\
    \limseq{\p{|X_n - \alpha| \geq \varepsilon}} &\leq \limseq{\frac{1}{\varepsilon^2}} \Var{X_n} \\
    \limseq{\p{|X_n - \alpha| \geq \varepsilon}} &\leq 0 \\ 
    \limseq{\p{|X_n - \alpha| \geq \varepsilon}} &= 0 \\ 
    X_n \overset{\text{P}} \longrightarrow \alpha
\end{align*}

# 3.
Seja $X, X_1, X_2, X_3, \dots$ sequência de variáveis aleatórias tal que $X_n = \dfrac{n}{n+1} X$, para todo $n$.

Mostre que a sequência converge em média quadrática para zero se $\E{X^2} < \infty$, mas não em caso
contrário.

\begin{align*}
    X_n \overset{r = 2} \longrightarrow 0
    &\implies \limseq{\E{|X_n - 0|^2}} = 0 \\
    &\implies \limseq{\E{X_n^2}} = 0 \\
    &\implies \limseq{\dfrac{n^2}{(n+1)^2} \E{X^2}} = 0 \\
    &\implies \E{X^2} = 0
\end{align*}

$X_n \overset{r = 2} \longrightarrow 0$ apenas quando $\E{X^2} = 0$.

{{< pagebreak >}}

# 4.
Seja ($X_n$) sequência de variáveis aleatórias discretas tal que

$$
\p{X_n = 0} = 1 - \dfrac{1}{n^2}, \; \p{X_n = n} = \dfrac{1}{n^2}, \; \forall n
$$

Prove que $X_n \overset{\text{q.c.}} \longrightarrow 0$.

$$
\sum_{n = 1}^\infty \p{X_n = n} = \sum_{n = 1}^\infty \dfrac{1}{n^2} = \dfrac{\pi^2}{6} < \infty
$$

Pelo lema de Borel-Cantelli, $\p{\lim \sup [X_n = n]} = 0$

\begin{align*}
    \p{\lim \sup [X_n = n]} = 0
    &\implies \p{\lim \sup [X_n > \varepsilon]} = 0 \\
    &\implies \p{\lim \sup [|X_n - 0| > \varepsilon]} = 0 \\
    &\implies X_n \overset{\text{q.c.}} \longrightarrow 0
\end{align*}

{{< pagebreak >}}

# 5.
Para $n \geq 1$, sejam $X_n \sim \text{Unif}(0,1)$ variáveis aleatórias i.i.d. Defina $Y_n = X_{(1)} = \min \lbrace X_1, X_2, \dots, X_n \rbrace$ e $U_n = n Y_n$. Mostre que

## a)
$Y_n \overset{\text{P}} \longrightarrow 0$.

::: {layout-ncol=3}
\begin{align*}
    &F_{Y_n}(y) \\
    &= 1 - (1 - F_{X_n}(y))^n \\
    &= 1 - (1 - y)^n 
\end{align*}

\begin{align*}
    &\p{Y_n > \varepsilon} \\
    &= 1 - \p{Y_n < \varepsilon} \\
    &= 1 - F_{Y_n}(\varepsilon) \\
    &= (1 - \varepsilon)^n
\end{align*}

\begin{align*}
    &\limseq{\p{|Y_n - 0| > \varepsilon}} \\
    &= \limseq{\p{Y_n > \varepsilon}} \\
    &= \limseq{(1- \varepsilon)^n} \\
    &= 0
\end{align*}
:::

$\limseq{\p{|Y_n - 0| > \varepsilon}} = 0$, portanto $Y_n \overset{\text{P}} \longrightarrow 0$.

## b)
$U_n \overset{\text{D}} \longrightarrow U$, sendo $U \sim \text{Exp}(1)$.

::: {layout-ncol=2}
\begin{align*}
    F_{U_n}(u) 
    &= \p{U_n \leq u} \\
    &= \p{n Y_n \leq u} \\
    &= \p{Y_n \leq \frac{u}{n}} \\
    &= F_{Y_n} \left( \frac{u}{n} \right) \\
    &= 1 - \left( 1 - \frac{u}{n} \right)^n
\end{align*}

\begin{align*}
    \limseq{F_{U_n}(u)} 
    &= \limseq{1 - \left(1 - \frac{u}{n} \right)^n} \\
    &= 1 - e^{-u} \\
    &= F_U(u)
\end{align*}
:::

$\limseq{F_{U_n}(u)} = F_U(u)$, portanto $U_n \overset{\text{D}} \longrightarrow U$.

{{< pagebreak >}}

# 6.
Seja ($X_n$) sequência de variáveis aleatórias. Mostre que

## a)
Se $X_n$ não converge em probabilidade para 0, então $\displaystyle \sum_{n = 1}^\infty \p{|X_n| > \varepsilon} = \infty$

\begin{align*}
    X_n \overset{\text{P}} \nrightarrow 0 
    &\implies \lim_{n \to \infty} \p{|X_n| > \varepsilon} \neq 0 \\
    &\implies \sum_{n = 1}^\infty \p{|X_n| > \varepsilon} \longrightarrow \infty 
\end{align*}

Pois séries de sequências que não convergem para 0 divergem.

## b) 
Se as variáveis aleatórias são independentes e $X_n \overset{\text{q.c.}} \longrightarrow 0$, então, para todo $\varepsilon > 0$, temos que $\displaystyle \sum_{n = 1}^\infty \p{|X_n| > \varepsilon} < \infty$

\begin{align*}
    X_n \overset{\text{q.c.}} \longrightarrow 0 
    &\implies \p{\lim \sup [|X_n| > \varepsilon]} = 0 \\
    &\implies \sum_{n = 1}^\infty \p{|X_n| > \varepsilon} < \infty
\end{align*}

Pois são independentes e pelo lema de Borel-Cantelli.

{{< pagebreak >}}

# 7.
Seja ($X_n$) sequência de variáveis aleatórias independentes tal que $X_n \sim \text{Bernoulli}(1/n), \; \forall n$.

Mostre que $X_n \overset{\text{P}} \longrightarrow 0$ porém $X_n$ não converge para zero q.c.

\begin{align*}      
    \sum_{n = 1}^\infty \p{|X_n| > \varepsilon} 
    &= \sum_{n = 1}^\infty 1 - \p{X_n \leq \varepsilon} \\
    &= \sum_{n = 1}^\infty 1 - F(\varepsilon) \\
    &= \sum_{n = 1}^\infty 1 - (1 - 1/n) \\
    &= \sum_{n = 1}^\infty 1/n \longrightarrow \infty \\
    &\implies \p{\lim \sup [|X_n| > \varepsilon]} = 1 \neq 0 \\
    &\implies X_n \overset{\text{q.c.}} \nrightarrow 0
\end{align*}

Pois são independentes e pelo lema de Borel-Cantelli.

# 9.
Seja ($X_n$) sequência de variáveis aleatórias, sendo $X_n \sim \text{Unif}(a, b_n), \forall n$. Se $b_n \longrightarrow a$ quando $n \to \infty$, mostre que $X_n \overset{\text{D}} \longrightarrow a$.

\begin{align*}
    \lim_{n \to \infty} F_{X_n}(x) 
    &= \lim_{n \to \infty} \left \lbrace \begin{array}{ll} 
        0, & \text{se} \; x < a \\
        \dfrac{x - a}{b_n - a}, & \text{se} \; a \leq x < b_n \\
        1, & \text{se} \; x \geq b_n
    \end{array} \right. \\
    &= \left \lbrace \begin{array}{ll} 
        0, & \text{se} \; x < a \\
        1, & \text{se} \; x \geq a
    \end{array} \right. \\
    &= F_a(x) \\
    &\implies X_n \overset{\text{D}} \longrightarrow a
\end{align*}

{{< pagebreak >}}

# 8.
Seja ($\Omega, \; \mathcal F, \; \text{P}$), em que $\Omega = (0, 1], \; \mathcal F = \mathbf \beta (0,1]$ (borelianos no intervalo $(0, 1]$) e $\text{P}$ é a medida de Lebesgue em $(0, 1]$, ou seja, para todo $0 < a < b \leq 1$, temos que $\p{(a, b]} = b - a$. Para cada n, seja $X_n = n \mathbb 1_{(0,1/n^2]}$.

## a)
Mostre que $X_n \overset{\text{q.c.}} \longrightarrow 0$.

\begin{align*}
    \p{\lim \sup [|Xn| > \varepsilon]} 
    &= \p{\lim \sup [n \mathbb 1_{(0,1/n^2]} > \varepsilon]} \\
    &= \p{\lim \sup [\mathbb 1_{(0,1/n^2]} > \varepsilon / n]} \\
    &= \p{\lim \sup [\mathbb 1_{(0,1/n^2]} = 1]} \\
    &= \p{\lim \sup (0,1/n^2]} \\
    &= \p{(0,0]} \\
    \p{\lim \sup [|Xn| > \varepsilon]} &= 0 \\
    &\implies X_n \overset{\text{q.c.}} \longrightarrow 0
\end{align*}


## b)
Para que valores de $r$ temos que $X_n \overset{\text{r}} \longrightarrow 0$?

::: {layout-ncol=2}
\begin{align*}
    \lim_{n \to \infty} \E{|X_n|^r}
    &= \lim_{n \to \infty} \E{(n \mathbb 1_{(0,1/n^2]})^r} \\
    &= \lim_{n \to \infty} n^r \E{(\mathbb 1_{(0,1/n^2]})} \\
    &= \lim_{n \to \infty} n^r \p{(0,1/n^2]} \\
    &= \lim_{n \to \infty} n^r / n^2 \\
    &= \lim_{n \to \infty} n^{r-2}
\end{align*}

\begin{align*}
    X_n \overset{\text{r}} \longrightarrow 0
    &\Longleftrightarrow \lim_{n \to \infty} \E{|X_n|^r} = 0 \\
    &\Longleftrightarrow \lim_{n \to \infty} n^{r-2} = 0\\
    &\Longleftrightarrow r-2 < 0 \\
    &\Longleftrightarrow r < 2 \\
    &\Longleftrightarrow r = 1, \; \text{pois} \; r \in \mathbb N^*
\end{align*}
:::

$X_n \overset{\text{r}} \longrightarrow 0$ apenas para $r = 1$.

{{< pagebreak >}}

# 10.
Seja ($X_n$) sequência de variáveis aleatórias, em que para cada $n, \; X_n$ tem função de distribuição acumulada dada por

$$
F_{X_n}(x) = \left \lbrace \begin{array}{ll}
    0, & \text{se} \; x < 0 \\
    1 - \left( 1 - \dfrac{\lambda x}{n} \right)^n, & \text{se} \; 0 \leq x < n / \lambda \\
    1, & \text{se} \; x \geq n / \lambda
\end{array} \right.
$$

em que $\lambda > 0$. Mostre que $X_n \overset{\text{D}} \longrightarrow X$, sendo $X \sim \text{Exp}(\lambda)$.

\begin{align*}
    \lim_{n \to \infty} F_{X_n}(x)
    &= \lim_{n \to \infty} \left \lbrace \begin{array}{ll}
        0, & \text{se} \; x < 0 \\
        1 - \left( 1 - \dfrac{\lambda x}{n} \right)^n, & \text{se} \; 0 \leq x < n / \lambda \\
        1, & \text{se} \; x \geq n / \lambda
    \end{array} \right. \\
    &= \left \lbrace \begin{array}{ll}
        0, & \text{se} \; x < 0 \\
        1 - e^{-\lambda x}, & \text{se} \; x \geq 0 \\
    \end{array} \right. \\
    &= F_X(x) \\
    &\implies X_n \overset{\text{D}} \longrightarrow X
\end{align*}

Pois $\displaystyle \lim_{n \to \infty} \left( 1 + \dfrac{a}{n} \right)^{bn} = e^{ab}$.