---
format: pdf
lang: pt
title: "Atividade 2"
subtitle: "Sequências e Séries de números reais. Séries de Taylor."
author: "Paulo Ricardo Seganfredo Campana"
date: "2023-03-20"
date-format: long
---
::: hidden
\def\limseq#1{{ \displaystyle \lim_{n \to \infty} #1 }}
\def\sumseq#1{{ \displaystyle \sum^{\infty} #1 }}
:::
---

# 1. 
Calcular os seguintes limites:

## a) $\limseq{\dfrac{n}{n+1}}$
$$
\limseq{\dfrac{n}{n+1}} = \limseq{\dfrac{1}{1 + \frac{1}{n}}} = \limseq{\dfrac{1}{1}} = 1
$$

## b) $\limseq{\dfrac{n+3}{n^3+4}}$
$$
\limseq{\dfrac{n+3}{n^3 + 4}} = \limseq{\dfrac{1 + \frac{3}{n}}{n^2 + \frac{4}{n}}} = \limseq{\dfrac{1}{n^2}} = 0
$$

## c) $\limseq{\dfrac{n^2+4n}{2n+3}}$
$$
\limseq{\dfrac{n^2+4n}{2n+3}} = \limseq{\dfrac{n+4}{2+\frac{3}{n}}} = \limseq{\dfrac{n+4}{2}} = \infty
$$
---

# 2. 
Provar que toda sequência periódica convergente é constante.

|       Se uma sequência $(x_n)$ é periódica de período $p$, isso significa que $(x_n)$ irá se repetir exatamente a cada $p$ termos e implica que $(x_n)$ terá no máximo $p$ termos distintos que se repetirão infinitamente, sendo assim $p$ pontos de acumulação.
|       Uma sequência convergente possui apenas 1 ponto de acumulação, portanto os $p$ pontos de uma sequência periódica devem ser iguais para haver convergência, o que torna $(x_n)$ uma sequência constante.
---

# 3. 
Provar a seguinte afirmação:

> Se $a = \limseq{x_n}$ e $b < a$, então, para $n$ suficientemente grande, tem-se $b < x_n$
> Analogamente, se $a < b$, então $x_n < b$ para todo $n$ suficientemente grande.

A partir da definição de convergência de uma sequência temos que:

$$
\forall \epsilon > 0, \; \exists n_0 \in \mathbb N : \; n > n_0 \implies |x_n - a| < \epsilon \implies a - \epsilon < x_n < a + \epsilon
$$

Sendo $b = a - \epsilon$, então $b < x_n$

E para $b = a + \epsilon$, então $b > x_n$
---

# 4. 
Obter os valores de aderência de $(x_n)$. Esta sequência converge?

$$
x_n = \left\lbrace \begin{matrix}
    (-1)^n, \text{ se } n \text{ for impar} \\ 
    1 + 1/n, \text{ se } n \text{ for par} \\
\end{matrix} \right.
$$

Tome as subsequências $(x_{2n-1})$ e $(x_{2n})$

\begin{align*}
    \limseq{x_{2n-1}} &= \limseq{(-1)^{2n-1}} = \limseq{-1} = -1 \\
    \limseq{x_{2n}} &= \limseq{1 + \dfrac{1}{2n}} = 1
\end{align*}

A sequência $(x_n)$ possui dois valores de aderência: $\lbrace -1,1 \rbrace$, portanto não converge.
---

# 5. 
Achar os valores de aderência da sequência:

$$
\dfrac{1}{2}, \dfrac{1}{3}, \dfrac{2}{3}, \dfrac{1}{4}, \dfrac{2}{4}, \dfrac{3}{4},
\dfrac{1}{5}, \dfrac{2}{5}, \dfrac{3}{5}, \dfrac{4}{5}, \dfrac{1}{6}, \dfrac{2}{6},
\dfrac{3}{6}, \dfrac{4}{6}, \dfrac{5}{6}, \dfrac{1}{7}, \dots
$$

A sequência contém todas as combinações de frações $\dfrac{a}{b}$ com $a \neq b$, então terá infinitos valores de aderência:

Tome $c = ak$ e $d = bk, \; \forall k \in \mathbb Z$

Note que se $\dfrac{a}{b}$ é elemento da sequência, então $\dfrac{c}{d}$ também será, e $\dfrac{a}{b} = \dfrac{c}{d}$

Portanto, para qualquer elemento da sequência, existirá infinitos outros elementos com mesmo valor numérico, que caracteriza valor de aderência.
---

# 6. 

Mostre que os seguintes limites são satisfeitos:

## a) $\limseq{\dfrac{\log(n+1)}{\log(n)}} = 1$

$$
\limseq{\dfrac{\log(n+1)}{\log(n)}} = \displaystyle \lim_{x \to \infty} \dfrac{\log(x+1)}{\log(x)} = \displaystyle \lim_{x \to \infty} \dfrac{\dfrac{1}{x+1} \ln 10}{\dfrac{1}{x} \ln 10} = \displaystyle \lim_{x \to \infty} \dfrac{x}{x+1} = 1
$$

## b) $\limseq{\sqrt[n]{a}} = 1, \; a > 0$

$$
\limseq{\sqrt[n]{a}} = e^{\ln \limseq{\sqrt[n]{a}} } = e^{\limseq{\ln \sqrt[n]{a}}} = e^{\limseq{\dfrac{\ln a}{n}}} = e^{\ln a \limseq{\dfrac{1}{n}}} = e^0 = 1
$$

## c) $\limseq{\sqrt[n]{n}} = 1$

$$
\limseq{\sqrt[n]{n}} = e^{\ln \limseq{\sqrt[n]{n}} } = e^{\limseq{\ln \sqrt[n]{n}}} = e^{\limseq{\dfrac{\ln n}{n}}} = e^{\displaystyle \lim_{x \to \infty} \dfrac{\ln x}{x}} = e^{\displaystyle \lim_{x \to \infty} \dfrac{1}{x}} = e^0 = 1
$$

## d) $\limseq{\sqrt[n+p]{n}} = 1, \; \forall p \in \mathbb N$

$$
\sqrt[n+p]{1} \leq \sqrt[n+p]{n} \leq \sqrt[n]{n}, \; \forall p \in \mathbb N, \; \forall n \geq 1
$$
\begin{align*}
    \limseq{\sqrt[n+p]{1}} \leq &\limseq{\sqrt[n+p]{n}} \leq \limseq{\sqrt[n]{n}} \\
    1 \leq &\limseq{\sqrt[n+p]{n}} \leq 1 \\
    &\limseq{\sqrt[n+p]{n}} = 1 \\
\end{align*}
---

# 7. 
Achar o $\lim \inf x_n$ e o $\lim \sup x_n$ para cada uma das seguintes sequências:

### a) $x_n = \frac{1}{n}$

$x_n$ converge para 0, portanto $\lim \inf x_n = \lim \sup x_n = 0$

### b) $x_n = (-1)^n \frac{1}{n}$

$x_n$ converge para 0, portanto $\lim \inf x_n = \lim \sup x_n = 0$

### c) $x_n = (-1)^n (1 + \frac{1}{n})$

Tome as subsequências $(x_{2n-1})$ e $(x_{2n})$

\begin{align*}
    \limseq{x_{2n-1}} &= \limseq{(-1)^{2n-1} \left( 1 + \dfrac{1}{2n-1} \right)} = -\limseq{1 + \frac{1}{2n-1}} = -1 \\
    \limseq{x_{2n}} &= \limseq{(-1)^{2n} \left( 1 + \dfrac{1}{2n} \right)} = \limseq{1 + \dfrac{1}{2n}} = 1 \\
\end{align*}

$\lim \inf x_n = -1, \; \lim \sup x_n = 1$
---

# 8. 
Verificar que $\lim a_n = \lim b_n = 0$, porém $\sum a_n$ e $\sum b_n$ são divergentes.

## a) $a_n = \sqrt{n+1} - \sqrt{n}$

$$
\limseq{\sqrt{n+1} - \sqrt{n}} = \limseq{\dfrac{1}{\sqrt{n+1} + \sqrt{n}}} = 0
$$
$$
\sumseq{_{n=1} \sqrt{n+1} - \sqrt{n}} =
$$
\begin{align*}
               \sqrt2 &+ \sqrt3 + \cdots + \sqrt{n} + \sqrt{n+1} \\
    - \sqrt1 - \sqrt2 &- \sqrt3 - \cdots - \sqrt{n} \\
\end{align*}
$$
= \limseq{\sqrt{n+1}} - \sqrt1 = \infty
$$

## b) $b_n = \log \left( 1 + \dfrac{1}{n} \right)$

$$
\limseq{\log \left( 1 + \dfrac{1}{n} \right)} = \log \left( \limseq{1 + \dfrac{1}{n}} \right) = \log 1 = 0
$$
$$
\sumseq{_{n=1} \log \left( 1 + \dfrac{1}{n} \right)} = \sumseq{_{n=1} \log \left( \dfrac{n+1}{n} \right)} = \sumseq{_{n=1} (\log(n+1) - \log n)} =
$$
\begin{align*}
              \log2 &+ \log3 + \cdots + \log n + \log(n+1) \\
    - \log1 - \log2 &- \log3 - \cdots - \log n \\
\end{align*}
$$
= \limseq{\log(n+1) - \log1} = \infty
$$
---

# 9. 
Decidir se as seguintes séries são convergentes ou divergentes:

## a) $\sumseq{_{n=1} \dfrac{\sin (n \theta)}{n^2}}$

\begin{align*}
    \sumseq{_{n=1} \dfrac{-1}{n^2}} &\leq \sumseq{_{n=1} \dfrac{\sin (n \theta)}{n^2}} \leq \sumseq{_{n=1} \dfrac{1}{n^2}} \\
    -\dfrac{\pi^2}{6} &\leq \sumseq{_{n=1} \dfrac{\sin (n \theta)}{n^2}} \leq \dfrac{\pi^2}{6}
\end{align*}

Converge por ser limitada

## b) $\sumseq{_{n=2} \dfrac{1}{\sqrt[3]{n^2 - 1}}}$

$$
\sumseq{_{n=2} \dfrac{1}{\sqrt[3]{n^2 - 1}}} \geq \sumseq{_{n=2} \dfrac{1}{\sqrt[3]{n^2}}} \geq \sumseq{_{n=2} \dfrac{1}{n}} \to \infty
$$

Diverge por comparação

## c) $\sumseq{_{n=1} \dfrac{n^2}{n!}}$

$$
\limseq{\left| \dfrac{(n+1)^2}{(n+1)!} \dfrac{n!}{n^2} \right|} = \limseq{\dfrac{n+1}{n^2}} = \limseq{\dfrac{1 + \frac{1}{n}}{n}} = 0 < 1
$$

Converge pelo teste da razão

## d) $\sumseq{_{n=1} \dfrac{\log n}{n}}$

$$
\sumseq{_{n=1} \dfrac{\log n}{n}} \geq \sumseq{_{n=1} \dfrac{1}{n}} \to \infty
$$

Diverge por comparação

## e) $\sumseq{_{n=2} \dfrac{1}{\log n}}$

$$
\sumseq{_{n=2} \dfrac{1}{\log n}} \geq \sumseq{_{n=2} \dfrac{1}{n}} \to \infty
$$

Diverge por comparação


## f) $\sumseq{_{n=2} \dfrac{1}{(\log n)^n}}$

$$
\sumseq{_{n=2} \dfrac{1}{(\log n)^n}} \leq \sumseq{_{n=2} \dfrac{1}{2^n}} = \dfrac{\frac{1}{4}}{1 - \frac{1}{2}} = \dfrac{1}{2}
$$

Converge por comparação

## g) $\sumseq{_{n=2} \dfrac{1}{n^2 \log n}}$

$$
\sumseq{_{n=2} \dfrac{1}{n^2 \log n}} \leq \sumseq{_{n=2} \dfrac{1}{n^2}} \leq \sumseq{_{n=1} \dfrac{1}{n^2}} = \dfrac{\pi^2}{6}
$$

Converge por comparação

## h) $\sumseq{_{n=1} \dfrac{n^2}{n^3+1}}$

$$
\sumseq{_{n=1} \dfrac{n^2}{n^3+1}} = \sumseq{_{n=1} \dfrac{1}{n + \frac{1}{n^2}}} \geq \sumseq{_{n=1} \dfrac{1}{2n}} \to \infty
$$

Diverge por comparação

## i) $\sumseq{_{n=1} \dfrac{1}{n^r}}, \; r > 1$

$$
\displaystyle \int \limits_a^\infty \dfrac{1}{x^r} dx = \dfrac{x^{1-r}}{1-r} \Bigg|_a^\infty = \dfrac{1}{1-r} \lim_{x \to \infty} \left( x^{1-r} - a^{1-r} \right) < \infty, \; r > 1
$$

Converge pelo teste da integral
---

# 10.
Determine para quais valores de $x$ as seguintes séries são convergentes.

## a) $\sumseq{_{n=1} n^k x^n}, \; k \in \mathbb N$

$$
\limseq{\left| \dfrac{(n+1)^k x^{n+1}}{n^k x^n} \right|} = |x| \limseq{\left( 1 + \dfrac{1}{n} \right)^k} = |x| \left( \limseq{1 + \dfrac{1}{n}} \right)^k = |x|
$$

Converge para $|x| < 1$

## b) $\sumseq{_{n=1} \dfrac{x^n}{n^n}}$

$$
\limseq{\left| \dfrac{x^{n+1}}{(n+1)^{n+1}} \dfrac{n^n}{x^n} \right|} = |x| \limseq{\dfrac{n^n}{(n+1)^{n+1}}} 
$$
$$
= |x| \limseq{\dfrac{1}{n+1} \left( 1 - \dfrac{1}{n} \right)^n} = |x| \limseq{\dfrac{\frac{1}{e}}{n+1}} = 0
$$

Converge para todo $x$

## c) $\sumseq{_{n=1} n! \, x^n}$

$$
\limseq{\left| \dfrac{(n+1)! \, x^{n+1}}{n! \, x^n} \right|} = |x| \limseq{n+1} = \infty
$$

Diverge para todo $x$

## d) $\sumseq{_{n=1} \dfrac{x^n}{n^2}}$

$$
\limseq{\left| \dfrac{x^{n+1}}{(n+1)^2} \dfrac{n^2}{x^n} \right|} = |x| \limseq{\left( \dfrac{n}{n+1} \right)^2} = |x| \left( \limseq{1 - \dfrac{1}{n}} \right)^2 = |x|
$$

Converge para $|x| < 1$
---

# 11.
Obter a série de Taylor de ordem n das seguintes funções:

## a) $f(x) = e^x, \;$ em torno de $x = 0$

$$
f^{(n)}(x) = e^x, \; f^{(n)}(0) = e^0 = 1
$$
$$
f(x) = \sumseq{_{n=0} \dfrac{f^{(n)}(a)}{n!} (x-a)^n} = \sumseq{_{n=0} \dfrac{x^n}{n!}}
$$

## b) $f(x) = \log(1+x), \; x > -1, \;$ em torno de $x = 0$

$$
f'(x) = \dfrac{1}{1+x}, \; f''(x) = \dfrac{-1}{(1+x)^2}, \; f'''(x) = \dfrac{2}{(1+x)^3}, \; \cdots
$$
$$
f^{(n)}(x) = \dfrac{(-1)^{n-1}(n-1)!}{(1+x)^n}, \; f^{(n)}(0) = (-1)^{n-1}(n-1)!
$$
$$
f(x) = f(a) + \sumseq{_{n=1} \dfrac{f^{(n)}(a)}{n!} (x-a)^n} = \sumseq{_{n=1} \dfrac{(-1)^{n-1}(n-1)!}{n!} x^n} = \sumseq{_{n=1} \dfrac{(-1)^{n+1}}{n} x^n}
$$

## c) $f(x) = \dfrac{1}{x}, \; x > 0, \;$ em torno de $x = 2$

$$
f'(x) = \dfrac{-1}{x^2}, \; f''(x) = \dfrac{2}{x^3}, \; f'''(x) = \dfrac{-6}{x^4}, \; \cdots
$$
$$
f^{(n)}(x) = \dfrac{(-1)^n \, n!}{x^{n+1}}, \; f^{(n)}(2) = \dfrac{(-1)^n \, n!}{2^{n+1}}
$$
$$
f(x) = \sumseq{_{n=0} \dfrac{f^{(n)}(a)}{n!} (x-a)^n} = \sumseq{_{n=0} \dfrac{(-1)^n}{2^{n+1}} (x-2)^n}
$$
---

# 12.
Obter a série de Taylor, em torno do ponto $x = 0$, das seguintes funções:

## a) $f(x) = \dfrac{1}{1+x^2}, \;$ ordem $2n+1$

$$
f'(x) = \dfrac{-2x}{(1+x^2)^2}, \; \cdots
$$
$$
f'(0) = 0, \; f''(0) = -2, \; f'''(x) = 0, \; f''''(x) = 24, \; \cdots
$$
$$
f^{(n)}(0) = n! \, Re(i^n)
$$
$$
f(x) = \sumseq{_{n=0} \dfrac{f^{(n)}(a)}{n!} (x-a)^n} = \sumseq{_{n=0} Re(i^n) x^n}
$$
$$
f(x) = \sumseq{_{n=0} Re(i^{2n}) x^{2n}} = \sumseq{_{n=0} (-1)^n x^{2n}}
$$

## b) $f(x) = \sin x, \;$ ordem $2n+1$

$$
f'(x) = \cos x, \; f''(x) = -\sin x, \; f'''(x) = -\cos x, \; \cdots
$$
$$
f'(0) = 1, \; f''(0) = 0, \; f'''(0) = -1, \; \cdots
$$
$$
f^{(n)}(0) = Re(i^{n-1})
$$
$$
f(x) = \sumseq{_{n=0} \dfrac{f^{(n)}(a)}{n!} (x-a)^n} = \sumseq{_{n=0} \dfrac{Re(i^{n-1})}{n!} x^n}
$$
$$
f(x) = \sumseq{_{n=0} \dfrac{Re(i^{2n+1-1})}{(2n+1)!} x^{2n+1}} = \sumseq{_{n=0} \dfrac{(-1)^n}{(2n+1)!} x^{2n+1}}
$$

## c) $f(x) = \cos x, \;$ ordem $2n$

$$
f'(x) = -\sin x, \; f''(x) = -\cos x, \; f'''(x) = \sin x, \; \cdots
$$
$$
f'(0) = 0, \; f''(0) = -1, \; f'''(0) = 0, \; \cdots
$$
$$
f^{(n)}(0) = Re(i^{n})
$$
$$
f(x) = \sumseq{_{n=0} \dfrac{f^{(n)}(a)}{n!} (x-a)^n} = \sumseq{_{n=0} \dfrac{Re(i^{n})}{n!} x^n}
$$
$$
f(x) = \sumseq{_{n=0} \dfrac{Re(i^{2n})}{(2n)!} x^{2n}} = \sumseq{_{n=0} \dfrac{(-1)^n}{(2n)!} x^{2n}}
$$
---
